#!/bin/bash

Full_Scan() {
	ports=$1
	TitleMessage "Stage 3: Refined Scan" "sub"
	InfoMessage "Enumerating open ports"
	results=$(nmap -sC -sV -Pn -p"$ports" -oA "$resultsPath"/"$fullmachine" "$target")
	resultsFile="$resultsPath/$fullmachine.nmap"
	SuccessMessage "Scanning complete!"
	TitleMessage "Analysis"
	InfoMessage "Run ./naes -a [alias|ip address] to analyse the results!"
	InfoMessage "Full results can be found in ${YELLOW}$resultsPath${PLAIN}" 
}

Get_Open_Ports() {
	runtime=$(date)
	TitleMessage "Scanning" "main"
	echo "$runtime" > "$resultsPath/runtime"
	InfoMessage "Scan started at: ${YELLOW} $runtime ${PLAIN}"
	InfoMessage "Target IP: ${YELLOW}$target${PLAIN}"
	if [[ -n $fullmachine ]]; then
		InfoMessage "Alias: ${YELLOW}$fullmachine${PLAIN}"
	fi
	top_ports_nmap=$(nmap -sT --top-ports 1000 -Pn -T4 "$target")
	top_ports=$(echo "$top_ports_nmap" | grep "^[0-9]" | cut -d '/' -f 1,3)
	top_ports_formatted=$(echo "$top_ports_nmap" | grep "^[0-9]" | awk -F '/tcp' '{print $1 " " $2}' | awk '{print $1 " " $3}')
	TitleMessage "Stage 1: Common Ports" "sub"
	InfoMessage "Scanning the top 1000 ports with nmap"
	AlertMessage "Out of the top 1000 ports, the following responded as OPEN:"
	echo "$top_ports_formatted" | tee "$resultsPath"/$top_ports_file
	if [[ "$top_ports" == *"$http"* || "$top_ports" == *"$https"* || "$top_ports" == *"$althttp"* ]]; then
		if [[ "$top_ports" == *"$http"* ]]; then
			AlertMessage "Port 80 is open --> Check http://$target"
		fi
		if [[ "$top_ports" == *"$https"* ]]; then
			AlertMessage "Port 443 is open --> Check https://$target"
		fi
		if [[ "$top_ports" == *"$althttp"* ]]; then
			AlertMessage "Port 8080 is open --> Check http://$target:8080" 
		fi
	fi
	if [[ "$top_ports" == *"$dns"* && "$top_ports" == *"$kerb"* && "$top_ports" == *"$ldap"* ]]; then
		AlertMessage "$target could be a Domain Controller." 
		InfoMessage "Ports 88 (Kerberos), 53 (DNS) and 389 (LDAP) are open on the host"
	fi
	TitleMessage "Stage 2: All Ports" "sub"
	all_ports_nmap=$(nmap -sT -p- -Pn -T4 "$target")
	all_ports=$(echo "$all_ports_nmap" | grep "^[0-9]" | cut -d '/' -f 1,3)
	all_ports_formatted=$(echo "$all_ports_nmap" | grep "^[0-9]" | awk -F '/tcp' '{print $1 " " $2}' | awk '{print $1 " " $3}')
	if [[ "$top_ports" == "$all_ports" ]]; then
		FailedMessage "No new ports found"
		cp "$resultsPath"/$top_ports_file "$resultsPath"/$all_ports_file
	else
		SuccessMessage "More ports found!"
		AlertMessage "The following ports responded as OPEN"
		echo "$all_ports_formatted" | tee "$resultsPath"/$all_ports_file
	fi
	listofports=$(echo "$all_ports" | tr '\n' ',' | sed s/,$//)
	Full_Scan "$listofports"
}