#!/bin/bash
naesDir=$( dirname -- "$0"; )
source "$naesDir/.vars"
source "$modsFolder/utils"

Info
chmod +x -R "$binFolder"
CONFIG_FILE=".config"
if test -f "$CONFIG_FILE"; then
	seclists=$(awk '$1=="SecLists:"{print $2}' $CONFIG_FILE)
fi
if [[ -z $seclists ]] ; then
	seclists="/path/to/SecLists/folder"
fi

while getopts ":ht:a:e:" option; do
	case $option in
	h) # display Help
		Help
		exit
		;;
	t) # Enter a name
		target=$OPTARG
		source "$modsFolder/scan"
		source "$modsFolder/analyse"
		resultsPath="$outputFolder/$target"
		mkdir -p "$resultsPath"
		resultsFile=$resultsPath/$target.nmap
		Check_Exists
		Check_HTB
		printf "Target IP: ${YELLOW} %s${PLAIN}\n" "$target"
		Get_Open_Ports
		exit
		;;
	a) # Analyse module
		target=$OPTARG
		source "$modsFolder/analyse"
		Analyse_Results "$target"
		exit
		;;
	:) #Missing argument 
		FailedMessage "Error: -${OPTARG} requires an argument."
		if [[ ${OPTARG} = "t" ]]; then
		InfoMessage "Usage: naes -t [IP-ADDRESS]"
		elif [[ ${OPTARG} = "a" ]]; then
		InfoMessage: "Usage: naes -a [IP-ADDRESS]"
		fi
		;;
	*) # Invalid option
		args=$OPTARG
		FailedMessage "Invalid argument: $args"
		exit
		;;
	esac
done
