#!/bin/bash
naesDir="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
source "$naesDir/.vars"
source "$modsFolder/utils"

chmod +x -R "$binFolder"
CONFIG_FILE=".config"
if test -f "$CONFIG_FILE"; then
	seclists=$(awk '$1=="SecLists:"{print $2}' $CONFIG_FILE)
	hackscripts=$(awk '$1=="HackScripts:"{print $2}' $CONFIG_FILE)
fi
if [[ -z $seclists ]] ; then
	seclists="/path/to/SecLists/folder"
fi

while getopts "cht:a:e:" option; do
	case $option in
	c) # display Help
		CleanUp
		exit
		;;
	h) # display Help
		Help
		exit
		;;
	t) # Enter a name
		Info
		target=$OPTARG
		source "$modsFolder/scan"
		source "$modsFolder/analyse"
		TitleMessage "Starting NAES" "main"
		Check_HTB
		Get_Open_Ports
		exit
		;;
	a) # Analyse module
		target=$OPTARG
		source "$modsFolder/analyse"
		Analyse_Results "$target"
		exit
		;;
	:) #Missing argument 
		FailedMessage "Error: -${OPTARG} requires an argument."
		if [[ ${OPTARG} = "t" ]]; then
		InfoMessage "Usage: naes -t [IP-ADDRESS]"
		elif [[ ${OPTARG} = "a" ]]; then
		InfoMessage: "Usage: naes -a [IP-ADDRESS]"
		fi
		;;
	*) # Invalid option
		args=$OPTARG
		FailedMessage "Invalid argument: $args"
		exit
		;;
	esac
done
